In [ ]:
#curl http://lang.org.ua/static/downloads/models/news.lowercased.tokenized.word2vec.300d.bz2 --output news.lowercased.tokenized.word2vec.300d.bz2

In [2]:
from gensim.models import KeyedVectors

In [3]:
wv = KeyedVectors.load_word2vec_format('news.lowercased.tokenized.word2vec.300d', binary=False)

In [16]:
wv['слово']

array([-1.051761,  1.291391, -1.523058, -1.41006 ,  2.389802,  0.920531,
        0.617554,  1.474145, -1.751643, -1.231671,  0.371221, -1.845865,
        1.147765,  1.302904,  0.663426, -2.666374, -1.771474, -0.291701,
       -1.415619,  1.593758, -0.676816,  2.118196,  1.933269, -1.148194,
        2.069097, -1.153974, -3.502659, -1.194996, -1.341823, -0.335554,
        0.994108, -1.928629,  1.709864, -0.319086,  2.817571,  1.12982 ,
       -0.690466,  1.271324,  2.759196,  0.912678, -1.797075,  1.479134,
       -0.381145,  0.476962,  3.545671,  0.302352,  0.16805 , -1.169542,
        0.852357,  0.74663 , -0.747367, -0.103639, -1.621643,  4.023391,
        1.408881,  0.283164,  1.869256, -0.330952, -1.014365,  0.335069,
       -0.194234, -0.149169,  0.352855,  3.112059, -0.069174,  0.117488,
       -1.244228,  0.481817, -1.286378, -0.536736,  0.327597,  1.091876,
       -0.558641,  0.393407, -0.37084 , -0.070491, -1.228214, -2.010035,
       -0.976877, -0.869274, -2.192101, -0.871976, 

In [6]:
wv.most_similar('слово')

[('дієслово', 0.6502863764762878),
 ('слівце', 0.6484909653663635),
 ('словосполучення', 0.6456568241119385),
 ('гасло', 0.5913079977035522),
 ('слово**', 0.555127739906311),
 ("прислів'я", 0.5407627820968628),
 ('письмо', 0.5235773324966431),
 ('прізвище', 0.52119380235672),
 ('пророцтво', 0.5125285983085632),
 ('ремесло', 0.5058826804161072)]

In [15]:
wv.most_similar(positive=['король'], negative=['королева'])

[('чернівчанин', 0.46570682525634766),
 ('тернополянин', 0.45779889822006226),
 ('одесит', 0.4554581642150879),
 ('кримчанин', 0.4465011656284332),
 ('севастополець', 0.4451814293861389),
 ('сумчанин', 0.4426470696926117),
 ('лозинський', 0.44073382019996643),
 ('назаров', 0.4395408630371094),
 ('червоноградець', 0.43848729133605957),
 ('воєначальник', 0.43565329909324646)]

In [22]:
!ls 1551/

--Корчування-пнів.txt
ГЛ--Несанкціонована-торгівля-.txt
Не-працює-бювет.txt
Не-працює-вантажний--ліфт.txt
Не-видача-пасажирам-квитків--марш--таксі-.txt
Не-працює-пасажирський-ліфт.txt
Про-розгляд-звернень-громадян.txt
Інші-Подяки.txt
Інші-питання--пропозиції-щодо-роботи-міської-електрички.txt
Інші-питання-утримання-малих-архітектурних-форм-та-прилеглої-до-них-території.txt
Інші-технічні-недоліки-стану-ліфту.txt
Інші-порушення-громадського-порядку-і-громадської-безпеки.txt
Інші-провайдери-кабельного-телебачення.txt
Стан-зливосточних-систем-проїжджих-частин-та-тротуарів.txt
Порив-труб-у-квартирі-чи-будинку.txt
Порив-труб-у-підвальному-приміщенні.txt
Миття-вікон--вітрин--вітражів--дзеркальних-поверхонь--дверей.txt
Зміна-траси-існуючих-тролейбусних-маршрутів.txt
Виток-холодної-води-на-поверхню.txt
Вигул-тренування-тварин-у-невідведених-для-цього-місцях.txt
Вилов-безпритульних-тварин.txt
Ремонт--реконструкція-приміщень-навчальних-закладів.txt
Ремонт-і-заміна-трамвайних-колій.txt
Ремонт-і-об

In [38]:
import glob
from langdetect import detect

def is_uk(filename):
    with open(filename) as f:
        text = f.read()
        if text.strip():
            return detect(text) == 'uk'
        return False

files = [f for f in glob.glob("1551/*") if is_uk(f)]

files[:10]

['1551/Відсутність-опалення-в-навчальних-закладах.txt',
 '1551/Встановлення-огородження-зеленої-зони.txt',
 '1551/Не-працює-вантажний--ліфт.txt',
 '1551/Забруднення-повітря-від-невідомих-джерел.txt',
 '1551/Відсутність-або-незадовільний-стан-плафонів-у-під-їзді.txt',
 '1551/Утримання-підвалів--колясочних-технічних-поверхів.txt',
 '1551/Благоустрій-поховань-та-їх-санітарний-стан.txt',
 '1551/Питання--що-стосуються-завершення-опалювального-сезону.txt',
 '1551/Встановлення--розміщення--і-демонтаж-біотуалетів.txt',
 '1551/Бажаючі-отримати--Картки-киянина--КК--.txt']

In [40]:
len(files)

153

In [39]:
!cat '1551/Відсутність-опалення-в-навчальних-закладах.txt'

У другому мікрврайоні Оболонського району не було тепла, зараз частково зьявилося, в 605 садочку діти мерзли при температурі 10 градусів, хто буде відшкодовувати гроші на ліки? Що сказвли на гарячій лінії кіевенерго сьогодні з ранку, завіряють в оболонському районі все гаразд, ремонтні роботи відсутні, тепло завіряють в усіх садках 100 було ще с 5-го числа, брешуть! Прикріпляю до звернення фото, констатую сьгодні 8:00 в 605 садочку в яслях тепла не було, на термометрі в группі було 10 градусів, за садочком закінчуються ремонтні роботи! Розберітся з брехньою, хотілось за свої кошти отримувати своєчастну інформацію про аварії та вчасний перерозрахунок коштів за послуги, які були відсутні в Гавро 5а, та інших будинках!




In [48]:
import re

with open('1551/Відсутність-опалення-в-навчальних-закладах.txt') as f:
    print(list(filter(lambda w: w.strip() and w.isalpha(), re.split(r'[\,\;\.\"\!\?\s\:\-]', f.read()))))

['У', 'другому', 'мікрврайоні', 'Оболонського', 'району', 'не', 'було', 'тепла', 'зараз', 'частково', 'зьявилося', 'в', 'садочку', 'діти', 'мерзли', 'при', 'температурі', 'градусів', 'хто', 'буде', 'відшкодовувати', 'гроші', 'на', 'ліки', 'Що', 'сказвли', 'на', 'гарячій', 'лінії', 'кіевенерго', 'сьогодні', 'з', 'ранку', 'завіряють', 'в', 'оболонському', 'районі', 'все', 'гаразд', 'ремонтні', 'роботи', 'відсутні', 'тепло', 'завіряють', 'в', 'усіх', 'садках', 'було', 'ще', 'с', 'го', 'числа', 'брешуть', 'Прикріпляю', 'до', 'звернення', 'фото', 'констатую', 'сьгодні', 'в', 'садочку', 'в', 'яслях', 'тепла', 'не', 'було', 'на', 'термометрі', 'в', 'группі', 'було', 'градусів', 'за', 'садочком', 'закінчуються', 'ремонтні', 'роботи', 'Розберітся', 'з', 'брехньою', 'хотілось', 'за', 'свої', 'кошти', 'отримувати', 'своєчастну', 'інформацію', 'про', 'аварії', 'та', 'вчасний', 'перерозрахунок', 'коштів', 'за', 'послуги', 'які', 'були', 'відсутні', 'в', 'Гавро', 'та', 'інших', 'будинках']


In [89]:
import numpy as np
from nltk.probability import FreqDist

with open('uk_stopwords.txt') as f:
    STOP_WORDS = f.read().split()

def read_words(file):
    return list(filter(lambda w: w.strip() and w.isalpha(), re.split(r'[\,\;\.\"\!\?\s\:\-]', file.read())))

def file_2_vec(filename):
    with open(filename) as f:
        words = [w.lower().strip() for w in read_words(f)]
        fdist = FreqDist(words)
        vecs = []
        for w in words:
            if w in STOP_WORDS:
                continue
            try:
                vecs.append(wv[w]/fdist.freq(w))
            except KeyError as e:
                #print(w)
                pass
            
        return np.sum(vecs, axis=0)/len(vecs)

In [90]:
vec = file_2_vec('1551/Відсутність-опалення-в-навчальних-закладах.txt')

In [91]:
wv.most_similar(positive=[vec], topn=10)

[('котельні', 0.5573310852050781),
 ('будинках', 0.5301535725593567),
 ('опалення', 0.5141777396202087),
 ('будинки', 0.5064504146575928),
 ('котельнях', 0.5029921531677246),
 ('квартирах', 0.4992782771587372),
 ('медикаменти', 0.49607449769973755),
 ('лічильники', 0.4933841824531555),
 ('тепло', 0.49312031269073486),
 ('тепла', 0.4920947849750519)]

In [94]:
docvecs = []
for file in files:
    vec = file_2_vec(file)
    docvecs.append((file, vec, wv.most_similar(positive=[vec], topn=1)[0]))

docvecs

[('1551/Відсутність-опалення-в-навчальних-закладах.txt',
  array([-3.39992332e+01, -3.37191200e+01,  4.89417982e+00,  1.37163219e+01,
          1.54454403e+01, -1.97209930e+01,  1.41687059e+01, -2.90795898e+01,
         -2.30653172e+01, -4.03435059e+01, -4.22967796e+01, -4.40917931e+01,
          1.48985090e+01,  2.04747677e+01,  3.60845304e+00,  1.74186859e+01,
          1.46521425e+01, -1.19878645e+01, -1.04446115e+01,  5.23052597e+00,
          3.96811218e+01, -1.23650494e+01,  7.75008345e+00, -2.78073177e+01,
         -4.95695000e+01, -1.21608267e+01, -1.54774599e+01,  4.16089706e+01,
         -1.51205730e+01,  1.87990475e+01,  1.32350359e+01,  7.50883560e+01,
          2.67733526e+00,  4.71563148e+01,  4.72469597e+01,  3.81360197e+00,
         -2.55022297e+01, -7.09279823e+00, -1.73373091e+00,  1.26119051e+01,
          2.28757458e+01,  2.49211240e+00,  1.55338945e+01,  1.90352898e+01,
         -2.50930748e+01,  5.79128113e+01,  5.55864677e+01, -1.39604311e+01,
          3.8627372

In [106]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=0).fit([vec[1] for vec in docvecs])

In [107]:
print(kmeans.cluster_centers_)  

[[ -54.94386205    7.735969     15.6604109  ...    1.43187399
   -24.29657441  -24.84922421]
 [-276.88464355  123.62369537  289.02682495 ...  -24.6361618
   -70.27680016 -276.44160461]
 [ -19.37863439    4.06988319   -5.05130967 ...    2.96999381
    -6.06218807   -3.46146901]
 [-192.15513611 -226.24594116  278.10717773 ...  196.39710999
  -298.02383423 -433.78585815]
 [-116.18088953   20.04105744   31.27519568 ...   29.26413741
   -93.38617178  -96.13182713]]


In [108]:
[wv.most_similar(positive=[c], topn=1) for c in kmeans.cluster_centers_]

[[('воды', 0.6423697471618652)],
 [('деревья', 0.6872620582580566)],
 [('приміщення', 0.5048991441726685)],
 [('моей', 0.8010287284851074)],
 [('воды', 0.6953336000442505)]]

In [117]:
topic_vecs = kmeans.predict([vec[1] for vec in docvecs])

In [118]:
topic_vecs

array([2, 0, 2, 0, 2, 4, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 4, 0, 2, 2,
       2, 0, 4, 0, 4, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 2, 4, 2, 2, 0, 1, 0,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 4, 2, 4, 2, 2, 0, 2, 0, 2, 2, 2, 4,
       2, 2, 4, 0, 2, 4, 2, 2, 0, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 0, 2,
       2, 0, 4, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 3, 2, 2, 0, 0, 2, 0, 0, 2, 2, 4, 0, 2, 2, 2, 0],
      dtype=int32)

In [120]:
len(kmeans.cluster_centers_)

5

In [121]:
len(topic_vecs)

153

In [122]:
len(docvecs)

153

In [124]:
for i, t in enumerate(topic_vecs):
    topic = kmeans.cluster_centers_[t]
    vec = docvecs[i]
    print((vec[0], wv.most_similar(positive=[topic], topn=1)[0]))

('1551/Відсутність-опалення-в-навчальних-закладах.txt', ('приміщення', 0.5048991441726685))
('1551/Встановлення-огородження-зеленої-зони.txt', ('воды', 0.6423697471618652))
('1551/Не-працює-вантажний--ліфт.txt', ('приміщення', 0.5048991441726685))
('1551/Забруднення-повітря-від-невідомих-джерел.txt', ('воды', 0.6423697471618652))
('1551/Відсутність-або-незадовільний-стан-плафонів-у-під-їзді.txt', ('приміщення', 0.5048991441726685))
('1551/Утримання-підвалів--колясочних-технічних-поверхів.txt', ('воды', 0.6953336000442505))
('1551/Благоустрій-поховань-та-їх-санітарний-стан.txt', ('приміщення', 0.5048991441726685))
('1551/Питання--що-стосуються-завершення-опалювального-сезону.txt', ('приміщення', 0.5048991441726685))
('1551/Встановлення--розміщення--і-демонтаж-біотуалетів.txt', ('приміщення', 0.5048991441726685))
('1551/Бажаючі-отримати--Картки-киянина--КК--.txt', ('приміщення', 0.5048991441726685))
('1551/Зміна-траси-існуючих-тролейбусних-маршрутів.txt', ('приміщення', 0.504899144172668

('1551/Проведення-модернізації-заміни-ліфту.txt', ('приміщення', 0.5048991441726685))
('1551/Продаж-спиртних-слабоалкогольних-напоїв-та-тютюнових-виробів-особам-молодше---р-.txt', ('приміщення', 0.5048991441726685))
('1551/Незручності-для-проживання-мешканців-від-цілодобової-роботи-закладів-торгівлі.txt', ('приміщення', 0.5048991441726685))
('1551/Перевірка-законності-знищення-дерев.txt', ('приміщення', 0.5048991441726685))
('1551/Відпуск-інсуліну-за-пільговим-рецептом.txt', ('приміщення', 0.5048991441726685))
('1551/Технічне-обслуговування-систем-тепло---водопостачання-та-водовідведення-і-зливов.txt', ('воды', 0.6953336000442505))
('1551/Питання-освітлення-на-опорних-стовпах.txt', ('приміщення', 0.5048991441726685))
('1551/Ремонт-або-демонтаж-огородження-зеленої-зони.txt', ('приміщення', 0.5048991441726685))
('1551/Обслуговування-одиноких-непрацездатних-громадян.txt', ('приміщення', 0.5048991441726685))
('1551/Ремонт-квартир.txt', ('приміщення', 0.5048991441726685))
('1551/Перевірка-н